ethnicity_map = {'Algerian': 'Black',
 'Any Other Group': 'Other',
 'Asian and Chinese': 'Asian',
 'Bangladeshi': 'Asian',
 'Black African': 'Black',
 'Black British': 'Black',
 'British': 'White',
 'Caribbean': 'Black',
 'Chinese': 'Asian',
 'Cypriot (Part nt st)': 'White',
 'Ecuadorian': 'Other',
 'English': 'White',
 'Ethiopian': 'Black',
 'Filipino': 'Asian',
 'Ghanaian': 'Black',
 'Greek Cypriot': 'White',
 'Indian/British India': 'Asian',
 'Iranian': 'Other',
 'Italian': 'White',
 'Mixed Black': 'Black',
 'Mixed Caribbean': 'Black',
 'Nigerian': 'Black',
 'Not Given': 'Unknown',
 'Not Specified': 'Unknown',
 'Not Stated': 'Unknown',
 'OTHER ASIAN BACKGROU': 'Asian',
 'Other Asian Unspecif': 'Asian',
 'OTHER BLACK BACKGROU': 'Black',
 'Other Black Unspecif': 'Black',
 'Other Ethnic Group': 'Other',
 'Other Latin American': 'Other',
 'OTHER WHITE BACK GRO': 'White',
 'Other White Unspecif': 'White',
 'Other White/Mixed Eu': 'White',
 'Pakistani/British Pa': 'Asian',
 'Portuguese': 'White',
 'Somali': 'Black',
 'Spanish': 'White',
 'Sri Lankan': 'Asian',
 'Sudanese': 'Black',
 'Turkish': 'Other',
 'Ugandan': 'Black',
 'Vietnamese': 'Asian',
 'White Irish': 'White',
 'Former USSR Rep': 'White',
 'POLISH': 'White',
 'Iraqi': 'Other',
 'Albanian': 'Other',
 'Columbian': 'Other',
 'Scottish': 'White',
 'Not stated': 'Unknown',
 'OTHER MIXED BACKGROU': 'Mixed',
 'Welsh': 'White',
 'British Asian': 'Asian',
 'Caribbean Asian': 'Asian',
 'Eritrean': 'Black',
 'Turkish Cypriot': 'Other',
 'Sinhalese': 'Asian',
 'White and Asian': 'Asian',
 'Other Mixed': 'Mixed',
 'Mixed Asian': 'Asian',
 'Greek': 'White',
 'Arab': 'Other',
 'MULTIPLE CODES': 'MULTIPLE CODES',
 'Irish': 'White',
 'Japanese': 'Asian',
 'Middle East': 'Other',
 'Croatian': 'White',
 'Black and Asian': 'Mixed',
 'Black and White': 'Mixed'}
