# Generated by Django 3.2.10 on 2022-01-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedCATModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, unique=True)),
                ('model_path', models.CharField(max_length=255)),
                ('model_display_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Downloader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('use_case', models.TextField(max_length=200)),
                ('affiliation', models.CharField(max_length=100)),
                ('funder', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
