# Generated by Django 3.2.11 on 2022-04-05 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_downloader_medcatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='downloaded_file',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
