version: '3.4'

services:
  medcatweb:
    build:
        network: host
        context: ./webapp
    command: python /webapp/manage.py runserver 0.0.0.0:8000
    volumes:
            - ./webapp/db:/webapp/db
    ports:
      - "8001:8000"
    env_file:
            - ./envs/env_medmen
