version: '3.4'

services:
  medcatweb:
    build:
        network: host
        context: ./webapp
    command: >
      bash -c "/etc/init.d/cron start &&
               python /webapp/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./webapp:/webapp
      - medcat_data:/medcat_data
      - ./envs/env_backup:/etc/environment
    ports:
      - "80:8000"
    env_file:
      - ./envs/env_medmen
      - ./envs/env_backup
    tty: true

volumes:
  medcat_data:
    driver: local
