version: '3.4'

services:
  medcatweb:
    build:
        network: host
        context: ./webapp
    command: python /webapp/manage.py runserver 0.0.0.0:8000
    restart: 'always'
    volumes:
            - ./webapp/db:/webapp/db
            - medcat_data:/medcat_data
    ports:
      - "8001:8000"
    env_file:
            - ./envs/env_medmen
    tty: true

volumes:
  medcat_data:
    driver: local
